### ISSUE TITLE
Question: how to apply patch

### ISSUE THREAD

**Issue by mdm508** [joemerlino/ProtubeFucker#1]
Hey, I was wondering if you had time, could you please explain how I to apply the patch to the file?

**Comment by joemerlino** [comment]
This is just a tweak so you should be jailbroken. Just install the deb file using Filza

**Comment by mdm508** [comment]
Wow, lo fatto! Sei davvero bravo!

**Comment by joemerlino** [comment]
Enjoy! 👍
